version: "3.3"
services:
    adp:
        image: ktssr/impact-adp
        stdin_open: true
        ports:
            - "3000:3000"
        restart: always
        depends_on:
            - api
    admin:
        image: ktssr/impact-admin
        stdin_open: true
        ports:
            - "3500:3000"
        restart: always
        depends_on:
            - api
    api:
        image: ktssr/impact-api
        ports:
            - "4000:4000"
        restart: always
        depends_on:
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "5000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: impact_prod
            MYSQL_USER: impact
            MYSQL_PASSWORD: impact
        volumes:
            - impact-db:/var/lib/mysql    
volumes:
    impact-db:
        
    