export const CREATE_ADP_INITIATE = "CREATE_ADP_INITIATE";
export const CREATE_ADP_FAILED = "CREATE_ADP_FAILED";
export const CREATE_ADP_SUCCESS = "CREATE_ADP_SUCCESS";
export const UPDATE_ADP_DATA = "UPDATE_ADP_DATA";