export const FETCH_SMART_MART_INITIATE = "FETCH_SMART_MART_INITIATE";
export const FETCH_SMART_MART_FAILED = "FETCH_SMART_MART_FAILED";
export const FETCH_SMART_MART_SUCCESS = "FETCH_SMART_MART_SUCCESS";