export const UPDATE_CATEGORY_LIST_INITIATE = "UPDATE_CATEGORY_LIST_INITIATE";
export const UPDATE_CATEGORY_LIST_FAILED = "UPDATE_CATEGORY_LIST_FAILED";
export const UPDATE_CATEGORY_LIST_SUCCESS = "UPDATE_CATEGORY_LIST_SUCCESS";
// export const UPDATE_LOGOUT_SUCCESS = "UPDATE_LOGOUT_SUCCESS";