export const UPDATE_CITY_LIST_INITIATE = "UPDATE_CITY_LIST_INITIATE";
export const UPDATE_CITY_LIST_FAILED = "UPDATE_CITY_LIST_FAILED";
export const UPDATE_CITY_LIST_SUCCESS = "UPDATE_CITY_LIST_SUCCESS";
// export const UPDATE_LOGOUT_SUCCESS = "UPDATE_LOGOUT_SUCCESS";