export const UPDATE_ADMIN_PRODUCT_LIST_INITIATE = "UPDATE_ADMIN_PRODUCT_LIST_INITIATE";
export const UPDATE_ADMIN_PRODUCT_LIST_FAILED = "UPDATE_ADMIN_PRODUCT_LIST_FAILED";
export const UPDATE_ADMIN_PRODUCT_LIST_SUCCESS = "UPDATE_ADMIN_PRODUCT_LIST_SUCCESS";