export const UPDATE_LOGIN_INITIATE = "UPDATE_LOGIN_INITIATE";
export const UPDATE_LOGIN_FAILED = "UPDATE_LOGIN_FAILED";
export const UPDATE_LOGIN_SUCCESS = "UPDATE_LOGIN_SUCCESS";
export const UPDATE_LOGOUT_SUCCESS = "UPDATE_LOGOUT_SUCCESS";