export const UPDATE_SUB_CATEGORY_LIST_INITIATE = "UPDATE_SUB_CATEGORY_LIST_INITIATE";
export const UPDATE_SUB_CATEGORY_LIST_FAILED = "UPDATE_SUB_CATEGORY_LIST_FAILED";
export const UPDATE_SUB_CATEGORY_LIST_SUCCESS = "UPDATE_SUB_CATEGORY_LIST_SUCCESS";
export const UPDATE_SUB_CATEGORY_SELECTED_CATEGORY = "UPDATE_SUB_CATEGORY_SELECTED_CATEGORY";