const adminOnlyApi = [
  "/list-city",
  "/add-city",
  "/admin/total-turnover",
  "/admin/monthly-turnover",
  "/admin/total-money",
  "/admin/monthly-money",
  "/admin/total-adp",
  "/admin/new-adp",
  "/admin/new-joining-bv",
  "/admin/get-champion-data",
  "/admin/get-champion-qualifiers",
  "/admin/get-one-plus-one-data",
  "/admin/get-one-plus-cards",
  "/admin/get-total-orders",
  "/admin/get-orders-data",
  "/admin/get-message-lib-details",
  "/admin/update-message-library",
  "/admin/get-message-lib-defaults",
  "/admin/get-whatsapp-groups",
  "/admin/get-all-cylces",
  "/admin/get-cycle-incomes",
  "/admin/get-total-incomes",
  "/admin/adp-statement-details",
  "/admin/download-statement",
];

module.exports.adminOnlyApi = adminOnlyApi;
